### ISSUE TITLE
game froze

### ISSUE THREAD

**Issue by cenheidlon** [GingaaBread/Unity-Game-Jam-2022#129]
**Describe the bug**
I couldn't click on cards or place them. Only the shop and end turn buttons worked.

**To Reproduce**
1. Click on a card and hit discard
2. Somehow get the option to discard the card again? Not sure how this happened -- might have been clicking things too quickly?
3. Couldn't click cards anymore.

**Expected behavior**
The card should have discarded normally and I could have finished my turn and then continued play.

**Screenshots**
![Screenshot 2022-11-27 at 22 14 14](https://user-images.githubusercontent.com/119008588/204183843-bb1c508d-065d-4552-af18-c81f80ccbd1a.png)

**Desktop (please complete the following information):**
 - Browser [brave/chrome]

**Comment by GingaaBread** [comment]
Looks like there was a game-breaking exception thrown, which doesn't hide the discard panel

**Comment by ballardi** [comment]
My guess is that something might be interrupting the animation UIDiscardPanelOutNeutral animation so it never fires that method call on it's last frame? like perhaps it's even somehow possible at the moment to enqueue a discard panel to be shown before a current discard panel is finished showing or something.

I couldn't figure out how it all works with the FeedbackPanel logic with feedback queues, and all that. It might make it easier to debug if we separate the discard panel out into it's own panel (like the shop panel for example) instead of part of the feedbackpaenl framework. what do you think of doing that gino?

**Comment by ballardi** [comment]
I ran into this and saved the exception trace for whoever looks into fixing this:

ApplicationException: Trying to confirm the discard action before the system is ready.
CardManager.ConfirmDiscard () (at Assets/Scripts/CardManagement/CardManager.cs:146)
UIDiscardAnimation.ConfirmDiscardInCardManager () (at Assets/Scripts/UI/Cards/UIDiscardAnimation.cs:38)

**Comment by ballardi** [comment]
hopefully fixed. closing but after the next build gino makes, please do create a new ticket if you see that problem happen again.
